In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
!pip install torch
import torch
from torch import optim
import numpy as np

Requirement already satisfied: torch in c:\users\carpa\anaconda3\lib\site-packages (2.8.0)
Requirement already satisfied: filelock in c:\users\carpa\anaconda3\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\carpa\anaconda3\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\carpa\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in c:\users\carpa\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\carpa\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\carpa\anaconda3\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: setuptools in c:\users\carpa\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\carpa\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\carpa\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)

In [34]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [35]:
spaceship_clean=spaceship.drop(columns=["PassengerId", "Name"])

In [36]:
spaceship_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8492 non-null   object
 1   CryoSleep     8476 non-null   object
 2   Cabin         8494 non-null   object
 3   Destination   8511 non-null   object
 4   Age           8514 non-null   float64
 5   VIP           8490 non-null   object
 6   RoomService   8512 non-null   float64
 7   FoodCourt     8510 non-null   float64
 8   ShoppingMall  8485 non-null   float64
 9   Spa           8510 non-null   float64
 10  VRDeck        8505 non-null   float64
 11  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(5)
memory usage: 755.7+ KB

In [37]:
numerical_cols_df=spaceship_clean.select_dtypes(include=["number"]).columns
numerical_cols_df

Index(['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'], dtype='object')

In [38]:
spaceship_clean["Cabin"]=spaceship_clean["Cabin"].str.split("/")

In [39]:
spaceship_clean["Cabin"]=spaceship_clean["Cabin"].str[0]

In [40]:
spaceship_clean

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

In [41]:
print(spaceship_clean.isnull().sum())

HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Transported       0
dtype: int64

In [42]:
spaceship_clean = spaceship_clean.dropna()

In [43]:
print(spaceship_clean.isnull().sum())

HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

In [44]:
spaceship_clean

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

In [45]:
categorical_cols = spaceship_clean.select_dtypes(include=["object", "category"]).columns
categorical_cols

Index(['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP'], dtype='object')

In [46]:
spaceship_clean_encoded = pd.get_dummies(spaceship_clean, columns=categorical_cols, drop_first=True, dtype=int)

In [47]:
spaceship_clean_encoded

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_True,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,VIP_True
0,39.0,0.0,0.0,0.0,0.0,0.0,False,1,0,0,1,0,0,0,0,0,0,0,1,0
1,24.0,109.0,9.0,25.0,549.0,44.0,True,0,0,0,0,0,0,0,1,0,0,0,1,0
2,58.0,43.0,3576.0,0.0,6715.0,49.0,False,1,0,0,0,0,0,0,0,0,0,0,1,1
3,33.0,0.0,1283.0,371.0,3329.0,193.0,False,1,0,0,0,0,0,0,0,0,0,0,1,0
4,16.0,303.0,70.0,151.0,565.0,2.0,True,0,0,0,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,41.0,0.0,6819.0,0.0,1643.0,74.0,False,1,0,0,0,0,0,0,0,0,0,0,0,1
8689,18.0,0.0,0.0,0.0,0.0,0.0,False,0,0,1,0,0,0,0,0,1,0,1,0,0
8690,26.0,0.0,0.0,1872.0,1.0,0.0,True,0,0,0,0,0,0,0,0,1,0,0,1,0
8691,32.0,0.0,1049.0,0.0,353.0,3235.0,False,1,0,0,0,0,0,1,0,0,0,0,0,0
8692,44.0,126.0,4688.0,0.0,0.0,12.0,True,1,0,0,0,0,0,1,0,0,0,0,1,0

In [16]:
spaceship_clean_encoded['Transported'].value_counts()

Transported
True     3401
False    3363
Name: count, dtype: int64

In [48]:
numerical_cols=spaceship_clean_encoded.select_dtypes(include=["number"]).columns
numerical_cols

Index(['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'HomePlanet_Europa', 'HomePlanet_Mars', 'CryoSleep_True', 'Cabin_B',
       'Cabin_C', 'Cabin_D', 'Cabin_E', 'Cabin_F', 'Cabin_G', 'Cabin_T',
       'Destination_PSO J318.5-22', 'Destination_TRAPPIST-1e', 'VIP_True'],
      dtype='object')

In [49]:
X=spaceship_clean_encoded.drop(columns=["Transported"])
y=spaceship_clean_encoded["Transported"]

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [51]:
from sklearn.preprocessing import MinMaxScaler

In [52]:
scaler=MinMaxScaler() #scaling
scaler.fit(X_train)

MinMaxScaler()

In [53]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [56]:
y_pred = log_reg.predict(X_test_scaled)

In [57]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [65]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

In [66]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.7760532150776053
Precision: 0.797962648556876
Recall: 0.7186544342507645

In [67]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

y_train = np.array(y_train)
y_test = np.array(y_test)


y_train_tensor = torch.tensor(y_train, dtype=torch.float32).reshape(-1,1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).reshape(-1,1)

In [80]:
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self, input_size,hidden_size1,hidden_size2, output_size):
        super(SimpleNN, self).__init__()
        self.network = nn.Sequential(nn.Linear(input_size,hidden_size1),
                                     nn.ReLU(),
                                     nn.Linear(hidden_size1,hidden_size2),
                                     nn.ReLU(),
                                     nn.Linear(hidden_size2,output_size),
                                
                                    nn.Sigmoid())
    def forward(self, x):
        return self.network(x)

In [81]:
input_size = 19
hidden_size1 = 20
hidden_size2=11
output_size = 1

model = SimpleNN(input_size, hidden_size1,hidden_size2, output_size)

In [82]:
criterion = nn.BCELoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training the model
epochs = 1500
for epoch in range(epochs):
    model.train()  # Set the model to training mode

    # Forward pass
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [10/1500], Loss: 0.6941
Epoch [20/1500], Loss: 0.6898
Epoch [30/1500], Loss: 0.6854
Epoch [40/1500], Loss: 0.6805
Epoch [50/1500], Loss: 0.6749
Epoch [60/1500], Loss: 0.6681
Epoch [70/1500], Loss: 0.6597
Epoch [80/1500], Loss: 0.6494
Epoch [90/1500], Loss: 0.6371
Epoch [100/1500], Loss: 0.6226
Epoch [110/1500], Loss: 0.6071
Epoch [120/1500], Loss: 0.5918
Epoch [130/1500], Loss: 0.5774
Epoch [140/1500], Loss: 0.5643
Epoch [150/1500], Loss: 0.5527
Epoch [160/1500], Loss: 0.5427
Epoch [170/1500], Loss: 0.5336
Epoch [180/1500], Loss: 0.5254
Epoch [190/1500], Loss: 0.5185
Epoch [200/1500], Loss: 0.5124
Epoch [210/1500], Loss: 0.5070
Epoch [220/1500], Loss: 0.5019
Epoch [230/1500], Loss: 0.4970
Epoch [240/1500], Loss: 0.4916
Epoch [250/1500], Loss: 0.4854
Epoch [260/1500], Loss: 0.4790
Epoch [270/1500], Loss: 0.4730
Epoch [280/1500], Loss: 0.4667
Epoch [290/1500], Loss: 0.4608
Epoch [300/1500], Loss: 0.4554
Epoch [310/1500], Loss: 0.4506
Epoch [320/1500], Loss: 0.4462
Epoch [330/1500], Loss: 0.4423
Epoch [340/1500], Loss: 0.4386
Epoch [350/1500], Loss: 0.4353
Epoch [360/1500], Loss: 0.4322
Epoch [370/1500], Loss: 0.4294
Epoch [380/1500], Loss: 0.4269
Epoch [390/1500], Loss: 0.4247
Epoch [400/1500], Loss: 0.4227
Epoch [410/1500], Loss: 0.4209
Epoch [420/1500], Loss: 0.4193
Epoch [430/1500], Loss: 0.4178
Epoch [440/1500], Loss: 0.4163
Epoch [450/1500], Loss: 0.4150
Epoch [460/1500], Loss: 0.4139
Epoch [470/1500], Loss: 0.4128
Epoch [480/1500], Loss: 0.4119
Epoch [490/1500], Loss: 0.4110
Epoch [500/1500], Loss: 0.4101
Epoch [510/1500], Loss: 0.4093
Epoch [520/1500], Loss: 0.4086
Epoch [530/1500], Loss: 0.4079
Epoch [540/1500], Loss: 0.4072
Epoch [550/1500], Loss: 0.4065
Epoch [560/1500], Loss: 0.4059
Epoch [570/1500], Loss: 0.4053
Epoch [580/1500], Loss: 0.4047
Epoch [590/1500], Loss: 0.4042
Epoch [600/1500], Loss: 0.4037
Epoch [610/1500], Loss: 0.4032
Epoch [620/1500], Loss: 0.4027
Epoch [630/1500], Loss: 0.4022
Epoch [640/1500], Loss: 0.4018
Epoch [650/1500], Loss: 0.4013
Epoch [660/1500], Loss: 0.4009
Epoch [670/1500], Loss: 0.4005
Epoch [680/1500], Loss: 0.4002
Epoch [690/1500], Loss: 0.3998
Epoch [700/1500], Loss: 0.3994
Epoch [710/1500], Loss: 0.3988
Epoch [720/1500], Loss: 0.3983
Epoch [730/1500], Loss: 0.3979
Epoch [740/1500], Loss: 0.3974
Epoch [750/1500], Loss: 0.3970
Epoch [760/1500], Loss: 0.3966
Epoch [770/1500], Loss: 0.3962
Epoch [780/1500], Loss: 0.3959
Epoch [790/1500], Loss: 0.3955
Epoch [800/1500], Loss: 0.3952
Epoch [810/1500], Loss: 0.3949
Epoch [820/1500], Loss: 0.3945
Epoch [830/1500], Loss: 0.3942
Epoch [840/1500], Loss: 0.3939
Epoch [850/1500], Loss: 0.3936
Epoch [860/1500], Loss: 0.3933
Epoch [870/1500], Loss: 0.3930
Epoch [880/1500], Loss: 0.3928
Epoch [890/1500], Loss: 0.3926
Epoch [900/1500], Loss: 0.3924
Epoch [910/1500], Loss: 0.3922
Epoch [920/1500], Loss: 0.3920
Epoch [930/1500], Loss: 0.3918
Epoch [940/1500], Loss: 0.3916
Epoch [950/1500], Loss: 0.3914
Epoch [960/1500], Loss: 0.3912
Epoch [970/1500], Loss: 0.3911
Epoch [980/1500], Loss: 0.3909
Epoch [990/1500], Loss: 0.3908
Epoch [1000/1500], Loss: 0.3906
Epoch [1010/1500], Loss: 0.3904
Epoch [1020/1500], Loss: 0.3903
Epoch [1030/1500], Loss: 0.3901
Epoch [1040/1500], Loss: 0.3900
Epoch [1050/1500], Loss: 0.3899
Epoch [1060/1500], Loss: 0.3897
Epoch [1070/1500], Loss: 0.3896
Epoch [1080/1500], Loss: 0.3895
Epoch [1090/1500], Loss: 0.3893
Epoch [1100/1500], Loss: 0.3892
Epoch [1110/1500], Loss: 0.3891
Epoch [1120/1500], Loss: 0.3889
Epoch [1130/1500], Loss: 0.3887
Epoch [1140/1500], Loss: 0.3886
Epoch [1150/1500], Loss: 0.3884
Epoch [1160/1500], Loss: 0.3883
Epoch [1170/1500], Loss: 0.3881
Epoch [1180/1500], Loss: 0.3880
Epoch [1190/1500], Loss: 0.3879
Epoch [1200/1500], Loss: 0.3878
Epoch [1210/1500], Loss: 0.3877
Epoch [1220/1500], Loss: 0.3876
Epoch [1230/1500], Loss: 0.3875
Epoch [1240/1500], Loss: 0.3874
Epoch [1250/1500], Loss: 0.3873
Epoch [1260/1500], Loss: 0.3871
Epoch [1270/1500], Loss: 0.3870
Epoch [1280/1500], Loss: 0.3870
Epoch [1290/1500], Loss: 0.3868
Epoch [1300/1500], Loss: 0.3867
Epoch [1310/1500], Loss: 0.3866
Epoch [1320/1500], Loss: 0.3865
Epoch [1330/1500], Loss: 0.3864
Epoch [1340/1500], Loss: 0.3863
Epoch [1350/1500], Loss: 0.3862
Epoch [1360/1500], Loss: 0.3861
Epoch [1370/1500], Loss: 0.3860
Epoch [1380/1500], Loss: 0.3859
Epoch [1390/1500], Loss: 0.3858
Epoch [1400/1500], Loss: 0.3857
Epoch [1410/1500], Loss: 0.3856
Epoch [1420/1500], Loss: 0.3856
Epoch [1430/1500], Loss: 0.3855
Epoch [1440/1500], Loss: 0.3854
Epoch [1450/1500], Loss: 0.3853
Epoch [1460/1500], Loss: 0.3853
Epoch [1470/1500], Loss: 0.3852
Epoch [1480/1500], Loss: 0.3851
Epoch [1490/1500], Loss: 0.3850
Epoch [1500/1500], Loss: 0.3849

In [84]:
from sklearn.metrics import accuracy_score, recall_score

# Evaluate the model
#model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    predictions = model(X_test_tensor)#.numpy().astype(int)
    predictions = (predictions > 0.5).int()
    actuals = y_test_tensor.numpy()

accuracy = accuracy_score(actuals, predictions)
print(f'accuracy score: {accuracy:.4f}')

accuracy score: 0.7997